language: node_js
node_js: 6.11.3
install:
- npm install
- npm install hexo-cli -g
cache:
  apt: true
  directories:
  - node_modules
addons:
  ssh_known_hosts: git.coding.net
before_script:
  - npm install -g gulp
script:
- hexo clean
- hexo generate
branches:
  only:
  - source
env:
  global:
    secure:  "mJprA32KXZoDUbOFDVHWW48b+RvhKDhMJnEdmz0YmqAJYQ2dnWyYO8/bsVgiXaVLWv9Z3i+3VKYoxr1sY+xe9JKNgbT9C3uUIO8sMrttKir0lJin2oi0b3LfMRDbFFsMIWPVfcfGTaH5Q0nMV9hefLciAhzu/lWL/0C58TNYDk0giozBW/YeeRtCWyO0Kf9wzLxaB+h3sntZgpvvEiqvvxz1t9qnFRCu2gH6hN3ZXKEqTFe9Niq5J8M6OncIGDt9Llt/ue8HXhupO3fyCpy8w/N2tqpzWWNMamkvlOZXmYl5gLHHDKSURsO4Ye9dy6HpxRSurV4+8grjyIb6tDkwwGZAbUSyDR47rRm++140NQXVu53fSRDbyO2+ywtKr7rS9AKYx2vGIB5HI8tw/uS5q1iG/onaQsL6AyN8DOeyvQnqrHw4MnLswdeC9q9qQNMPNaOqxcjf04Omv+oTTPums6G/fCILsngsUWU1mTRTEww64b2liEI0ROPUoLeZeVzz4nWB/1cqdceQJvoOga08Itqk6bxuCRHZjpz9uTp2v82p7QCdKpu5dN/EPHtkiRKEjqUD4x4n72TrTXStVhV4ew23IWT5PnNMMtJxmnewigrQ0dbB8up5rxh1/fAWq6Q5QfygWbQyLZtyWix+mHD1KiOI/M549wGC0/mwk9Dbmvw="
before_install:
- openssl aes-256-cbc -K $encrypted_0073154072eb_key -iv $encrypted_0073154072eb_iv
  -in .travis/4gcbdg.enc -out ~/.ssh/4gcbdg -d
deploy:
  provider: script
  script: sh .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: source
