# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 布袋小知诺
subtitle: 知行诺一
description: 易知 简能
author: zhinuo
language: zh-CN
timezone: Asia/Shanghai

# custom Site settings
# more detail check out docs
SEOTitle: 知诺 zhinuo 布袋小知诺 布袋知诺 知行诺一
header-img:  # header-img.png 
email: imovomi@gmail.com # your email
# email: brux4me@gmail.com # your email
keyword: 知诺 布袋小知诺 布袋知诺 zhinuo 知行诺一 # your keywords
# custom end


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
# url: http://www.zhinuo.space
# url: http://bdg.zhinuo.space
url: https://www.zhinuo.site
root: / 
permalink: article/:abbrlink.html      # :category/:id.html   #:id-:title.html
permalink_default:
  lang: zh-CN

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Category & Tag 分类项为 单字 时 且 lang: zh-CN 下面的英语为翻译
default_category: uncategorized
category_map:
    记: writing
    悟: spark
    经: essence
    摘: excerpt
    杂: MISC
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY年MM月DD日
time_format: HH:mm:ss
date_format_full: YYYY年MM月DD日 @ HH:mm

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

topindex_generator:
  per_page: 10
  order_by: -date

jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: true
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: true
    excerpt: false
    categories: false
    tags: true
    
# Extensions
## Plugins: https://hexo.io/plugins/
Plugins:

# Miscellaneous

#sitemap
sitemap:
  path: sitemap.xml

#Feed Atom
feed:
  type: atom     # rss2
  path: atom.xml # rss2.xml
  limit: 1000000

## Themes: https://hexo.io/themes/
theme: next
# theme: next514ok

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: # github coding 同时部署
- type: git
  repo: 
     github: git@gitbdg:budaig/budaig.github.com.git,master   
     coding: git@codingbdg:budaig/budaig.git,coding-pages
- type: baidu_url_submitter

# Security
## https://github.com/MikeCoder/hexo-blog-encrypt 密码不能为纯数字
encrypt:
  enable: true
  default_abstract: 本文已隐藏, 请输入密码浏览.</br>
  default_message: 您好, 请输入密码浏览.

# abbrlink config
abbrlink:
  alg: crc32  #support crc16(default) and crc32
  # rep: hex    #support dec(default) and hex
  # crc32 & hex e.g. https://post.zz173.com/posts/8ddf18fb.html
  # crc32 & dec e.g. https://post.zz173.com/posts/1690090958.html

baidu_url_submit:
  count: 3 ## 比如3，代表提交最新的三个链接
  host: www.zhinuo.site ## 在百度站长平台中注册的域名
  token: s9xxwoiUViShjVH0 ## 请注意这是您的秘钥，请不要发布在公众仓库里!
  path: baidu_urls.txt ## 文本文档的地址，新链接会保存在此文本文档里

# hexo default is empty, change to exact languages, and add xx.yml under your theme languages dir.
# language: [zh,en]
# # config hexo-generator-i18n option (optional, this is default option)
# i18n:
  # type: [page, post]
  # generator: [index, archive, category, tag]

# if your search is enable && search service is 'hexo'
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# auto prefixer
# autoprefixer:
  # exclude:
    # - '*.min.css'
  # browsers:
    # - 'last 2 versions'

symbols_count_time:
  symbols: true
  time: false
  total_symbols: false
  total_time: false

leancloud_counter_security:
  enable_sync: true
  app_id: <<your app id>>
  app_key: <<your app key>>
  username: <<your username>> # Will be asked while deploying if is left blank
  password: <<your password>> # Recommmended to be left blank. Will be asked while deploying if is left blank


restful:
  # site 可配置为数组选择性生成某些属性
  # site: ['title', 'subtitle', 'description', 'author', 'since', email', 'favicon', 'avatar']
  site: true        # hexo.config mix theme.config
  posts_size: 10    # 文章列表分页，0 表示不分页
  posts_props:      # 文章列表项的需要生成的属性
    title: true
    slug: true
    date: true
    updated: true
    comments: true
    path: true
    excerpt: false
    cover: true      # 封面图，取文章第一张图片
    content: false
    keywords: false
    categories: true
    tags: true
  categories: true         # 分类数据
  use_category_slug: false # Use slug for filename of category data
  tags: true               # 标签数据
  use_tag_slug: false      # Use slug for filename of tag data
  post: true               # 文章数据
  pages: false             # 额外的 Hexo 页面数据, 如 About


# hexo-generator-amp
# The following settings is the quick start options.
generator_amp:
  templateDir: amp-template
  assetDistDir: amp-dist
  logo:
    path: sample/logoznhs.png
    width: 120   #<= 600 px
    height: 20   #<= 60 px
  logo_topImage:                                  #(optional)
    path:   sample/logoznvs.png       #(optional)
    width:  150                                  #(optional)
    height: 150                                   #(optional)
  substituteTitleImage:
    path: sample/substituteTitleImage.jpg
    width: 220   #>= 696 px
    height: 150
  warningLog: false   # To display warning, please set true.
  placeholderImg:                                 #(optional)
    path: sample/sample-placeholder.png
  cssFilePath: sample/sample-amp.css         #(optional) Location of css or stylus or sass file to use
  templateFilePath: sample/sample-amp.ejs         #(optional) Location of ejs or pug template file to use
  generateAmpPath: amp/article/:abbrlink.html  #(optional) Custom AMP HTML Path
  # # Sample Template's option
  theme:                                        #(optional) Sample AMP template's option
     menu:                                      #(optional) Sample AMP template's menu option
       intro: /intro                #(optional) example menu
       archives: /archives                      #(optional) example menu
     # facebook_app_id: 1234567890                #(optional) api_id is necessary with the facebook's social button.
     # facebook_admins: 1234567890                #(optional) admins is necessary with the facebook's social button.
     # share_button:                              #(optional) Share button option
       # twitter: true                            #(optional) Enable Twitter share button
       # facebook: true                           #(optional) Enable Facebook share button
       # google: true                             #(optional) Enable Goolge+ share button
       # hatena: true                             #(optional) Enable Hatena share button
       # tumblr: true                             #(optional) Enable Tumblr share button
     category_posts: true                  #(optional) Enable category posts
     category_posts_detailed: true              #(optional) Enable detailed category posts
     latests: true                              #(optional) Enable latests posts
     list_limts: 6                              #(optional) This option limit the number of display in the above lists (default:5)
     authorLink:                          #(optional) Enable footer profile link
       mail_url: budaig@outlook.com
       # twitter_id: xxx
       # facebook_id: xxx
       # youtube_channel: xxx
       # instagram_id: xxx
       github_id: budaig
  # 6. Cache Option
  cache: hexo-generator-amp-cached.json           #(optional) Enable cache (Improve generation speed)
  # onlyForDeploy: false                          #(optional) #Deprecated <= v1.0.3
  # 7. Automatically validate AMP HTML
  validateAMP: true                               #(optional)
# 8. Footer Option (authorDetail)
# authorDetail:
  # authorReading: Your name description            #(optional)
  # avatar:                                         #(optional)
    # path:   sample/sample-avator.png              #(optional)
    # width:  150                                   #(optional)
    # height: 150                                   #(optional)
  # description: Self introduction                  #(optional)
# copyright_notice: The footer copyright notice     #(optional)