name: RXZ2GC

on:
  push:
    branches: 
      - source

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout codes
      uses: actions/checkout@v4

    - name: Enable corepack
      run: corepack enable

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'yarn'

    - name: Set Yarn version
      run: |
        yarn set version berry
        yarn config get enableGlobalCache

    - name: Install dependencies
      run: |
        yarn add hexo-cli
        yarn dlx hexo-cli
        yarn install

    - name: Configure Yarn PnP
      run: |
        yarn config set nodeLinker pnp
        yarn config set pnpMode loose

    - name: Get Latest Commit Message
      run: |
        git log --pretty=format:"%s from Github Actions at `date +"%Y-%m-%d %H:%M:%S"`" --date=short -n 1 > commit-message.log

    - name: Generate public files
      run: |
        yarn dlx hexo clean
        yarn dlx hexo generate
        # hexo clean
        # hexo generate

    - name: Deploy 2 github
      env:
        Github_Pages: github.com/budaig/budaig.github.com.git
        Github_Token: ${{ secrets.token_GitAPI }}
      # 将编译后的博客文件推送到指定仓库
      run: |
        git config --global user.name "budaig"
        git config --global user.email "imovomi@gmail.com"
        git clone https://${Github_Pages} .github_pages
        cd .github_pages
        git checkout -b master
        cd ../
        mv .github_pages/.git/ ./public/
        cd ./public/
        git add .
        git commit -F ../commit-message.log
        git push --force --quiet "https://${Github_Token}@${Github_Pages}" master:master

    - name: Deploy 2 Coding
      env:
        Coding_Pages: e.coding.net/budaim/budaim.git
        Coding_Token: ${{ secrets.token_CodinAPI }}
        Coding_Username: ${{ secrets.User_Codin }}
      # 将编译后的博客文件推送到指定仓库
      run: |
        git config --global user.name "budaim"
        git config --global user.email "brux@qq.com"
        git clone https://${Coding_Username}:${Coding_Token}@${Coding_Pages} .coding_pages
        cd .coding_pages
        git checkout -b master 
        #git checkout -b coding-pages
        cd ../
        rm -r ./public/.git/
        mv .coding_pages/.git/ ./public/
        cd ./public/
        git add .
        git commit -F ../commit-message.log
        git push --force --quiet "https://${Coding_Username}:${Coding_Token}@${Coding_Pages}" master:master
        # git push --force --quiet "https://${Coding_Username}:${Coding_Token}@${Coding_Pages}" coding-pages:coding-pages

